### ISSUE TITLE
Distance (mm) not converting from inches

### ISSUE THREAD

**Issue by JonathanUlrich** [EverythingSmartHome/everything-presence-addons#21] opened 2024-11-29 18:41 UTC
When Home assistant is set to Fahrenheit, pounds (US customary) in general settings, the Everything Presence Lite - Zone Configurator is not converting the distance properly to mm:
![EP Zone Config eng](https://github.com/user-attachments/assets/b9a47bc3-bd24-4557-a009-5712ac2cbfbd)
![EP Zone Config metric](https://github.com/user-attachments/assets/d76389ba-1a85-4bca-8393-e817b11cbe56)

**Comment by EverythingSmartHome** [comment] 2024-11-29 18:43
This is a duplicate of https://github.com/EverythingSmartHome/everything-presence-addons/issues/14

I will close this one in favour of that one

**Closed by EverythingSmartHome** 2024-11-29 18:43 UTC
